server:
  port: 9090
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
data:
  mongodb:
    host: localhost
    port: 27017
    database: hindalco

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
