spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:hindalco}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  port: ${SERVER_PORT:9090}
  
jwt:
  secret: ${JWT_SECRET:abcd123abcd123}
  expiration: ${JWT_EXPIRATION:3600000}
