spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

server:
  port: ${SERVER_PORT}