spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: hindalco

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
  
jwt:
  secret: abcd123abcd123
  expiration: 3600000