version: '3.0'

services:
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - hindalcoMonitring
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - hindalcoMonitring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning  # Mount the provisioning directory
    depends_on:
      - loki

networks:
  hindalcoMonitring:
    driver: "bridge"

volumes:
  loki_data:
    driver: local
  grafana_data:
    driver: local

