server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
- url: http://loki:3100/loki/api/prom/push

scrape_configs:
- job_name: discovery
  static_configs:
  - targets:
    - localhost
    labels:
      job: discovery
      __path__: /var/log/discovery-ms/*.log

- job_name: configserver
  static_configs:
  - targets:
    - localhost
    labels:
      job: configserver
      __path__: /var/log/configserver-ms/*.log

- job_name: apigateway
  static_configs:
  - targets:
    - localhost
    labels:
      job: apigateway
      __path__: /var/log/apigateway-ms/*.log

- job_name: userservice
  static_configs:
  - targets:
    - localhost
    labels:
      job: userservice
      __path__: /var/log/userservice-ms/*.log

- job_name: plantmicroservice
  static_configs:
  - targets:
    - localhost
    labels:
      job: plantmicroservice
      __path__: /var/log/plantservice-ms/*.log

- job_name: helperservice
  static_configs:
  - targets:
    - localhost
    labels:
      job: helperservice
      __path__: /var/log/helperservice-ms/*.log

- job_name: mongodb
  static_configs:
  - targets:
    - localhost
    labels:
      job: mongodb
      __path__: /var/log/mongodb/*.log
