apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryserver-deployments
  labels:
    app: discoveryserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discoveryserver
  template:
    metadata:
      labels:
        app: discoveryserver
    spec:
      containers:
      - name: discoveryserver
        image: hcorptech/discoveryserver:0.0.1
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discoveryserver
spec:
  selector:
    app: discoveryserver
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761

